import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import FloatingActions from "@/components/FloatingActions";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#0b1220]`}
      >
        <Navbar></Navbar>
        {/* Wrapper for content + top gradient */}
         <div className="relative min-h-screen overflow-hidden">
          {/* Top Semi-Sphere Cyan Gradient */}
          {/* <div className="absolute top-0 left-1/2 transform -translate-x-1/2
                          w-[200%] h-[30vh]
                          rounded-b-full
                          bg-cyan-400/50
                          blur-3xl
                          pointer-events-none
                          z-0" /> */}

          {/* Actual page content */}
          <div className="relative z-10">
            {children}
          </div>
        </div>
          <FloatingActions
          phone="+919187154521"
          whatsapp="+919187154521"
          whatsappMessage="Hi! I want a free consultation."
          chatbotHref="/chatbot"   // or "/contact"
          enquiryHref="/contact"
        />
        <Footer></Footer>
      </body>
    </html>
  );
}
